### ISSUE TITLE
HG1505 Validation

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4765]
Hey guys,

   * 21 April : pre-prod release candidate deployment
No new features after that date and I want to give validation results and green light until 30 of April (I will be on vacation till 6 of May). 

@jmarra13 * 5 May : production deployment and will require TW/Client/ASO deployment.

**Comment by jmarra13** [comment]
@juztas just added to my calendar.

**Comment by juztas** [comment]
https://github.com/dmwm/CRABServer/commit/4911b9c6176ba3645086b7b60ea5e719684b8376 @mmascher why this file movement is needed? Seems that this does not allow to start TW.
```
[crab3@vocms045 site-packages]$ ls
ApmonIf.py       DashboardAPI.py      HTCondorUtils.py   PSetTweaks                ProcInfo.pyc          WMCore
ApmonIf.pyc      DashboardAPI.pyc     HTCondorUtils.pyc  PandaServerInterface.py   RESTInteractions.py   apmon.py
CRABQuality.py   HTCondorLocator.py   Logger.py          PandaServerInterface.pyc  RESTInteractions.pyc  apmon.pyc
CRABQuality.pyc  HTCondorLocator.pyc  Logger.pyc         ProcInfo.py               TaskWorker            taskbuffer
[crab3@vocms045 site-packages]$ pwd
/data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.16.rc1/lib/python2.6/site-packages
```
after wget this file, TW started. Worth to check: https://github.com/dmwm/CRABServer/blob/master/setup.py

**Comment by juztas** [comment]
@mmascher is looking into this
```
 RESTSQL:DxyIhNHGntJV prepare [SELECT tm_taskname, panda_jobset_id, tm_task_status,                        tm_start_time, tm_start_injection, tm_end_injection,                        tm_task_failure, tm_job_sw, tm_job_arch, tm_input_dataset,                        tm_site_whitelist, tm_site_blacklist, tm_split_algo, tm_split_args,                        tm_totalunits, tm_user_sandbox, tm_cache_url, tm_username, tm_user_dn, tm_user_vo,                        tm_user_role, tm_user_group, tm_publish_name, tm_asyncdest, tm_dbs_url,                        tm_publish_dbs_url, tm_publication, tm_outfiles, tm_tfile_outfiles, tm_edm_outfiles,                        tm_job_type, tm_arguments, panda_resubmitted_jobs, tm_save_logs,                        tm_user_infiles, tw_name, tm_maxjobruntime, tm_numcores, tm_maxmemory, tm_priority, tm_activity,                        tm_scriptexe, tm_scriptargs, tm_extrajdl, tm_generator, tm_asourl, tm_events_per_lumi,                        tm_use_parent, tm_collector, tm_schedd, tm_dry_run,                        tm_user_files, tm_transfer_outputs, tm_output_lfn, tm_ignore_locality, tm_fail_limit, tm_one_event_mode                        FROM tasks WHERE tm_task_status = :get_status AND ROWNUM <= :limit AND tw_name = :tw_name]
[24/Apr/2015:14:43:43]  RESTSQL:DxyIhNHGntJV execute: () {'tw_name': 'vocms045', 'get_status': 'HOLDING', 'limit': 10}
[24/Apr/2015:14:43:43]  SERVER REST ERROR WMCore.REST.Error.ExecutionError e2bd8b92d2cea3394ddb0e7201077968 (Execution error)
[24/Apr/2015:14:43:43]    Traceback (most recent call last):
[24/Apr/2015:14:43:43]      File "/data/srv/beHG1505b/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.16.rc1/lib/python2.6/site-packages/WMCore/REST/Format.py", line 228, in stream_chunked
[24/Apr/2015:14:43:43]        for obj in stream:
[24/Apr/2015:14:43:43]      File "/data/srv/beHG1505b/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.16.rc1/lib/python2.6/site-packages/CRABInterface/RESTWorkerWorkflow.py", line 135, in get
[24/Apr/2015:14:43:43]        rows = self.api.query(None, None, self.Task.GetReadyTasks_sql, **binds)
[24/Apr/2015:14:43:43]      File "/data/srv/beHG1505b/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.16.rc1/lib/python2.6/site-packages/WMCore/REST/Server.py", line 2112, in query
[24/Apr/2015:14:43:43]        c, _ = self.execute(sql, *binds, **kwbinds)
[24/Apr/2015:14:43:43]      File "/data/srv/beHG1505b/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.16.rc1/lib/python2.6/site-packages/WMCore/REST/Server.py", line 2053, in execute
[24/Apr/2015:14:43:43]        return c, c.execute(None, *binds, **kwbinds)
[24/Apr/2015:14:43:43]    DatabaseError: ORA-00904: "TM_FAIL_LIMIT": invalid identifier
[24/Apr/2015:14:43:43]  SERVER HTTP ERROR cherrypy._cperror.HTTPError e18dd31953abc918230684e806214fb0 ((500, 'Execution error'))
[24/Apr/2015:14:43:43]    Traceback (most recent call last):
[24/Apr/2015:14:43:43]      File "/data/srv/beHG1505b/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.16.rc1/lib/python2.6/site-packages/WMCore/REST/Server.py", line 697, in default
[24/Apr/2015:14:43:43]        return self._call(RESTArgs(list(args), kwargs))
[24/Apr/2015:14:43:43]      File "/data/srv/beHG1505b/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.16.rc1/lib/python2.6/site-packages/WMCore/REST/Server.py", line 807, in _call
[24/Apr/2015:14:43:43]        return stream_maybe_etag(apiobj.get('etag_limit', self.etag_limit), etagger, reply)
[24/Apr/2015:14:43:43]      File "/data/srv/beHG1505b/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.16.rc1/lib/python2.6/site-packages/WMCore/REST/Format.py", line 475, in stream_maybe_etag
[24/Apr/2015:14:43:43]        raise cherrypy.HTTPError(int(err), message)
[24/Apr/2015:14:43:43]    HTTPError: (500, 'Execution error')
[24/Apr/2015:14:43:43] vocms0133.cern.ch 128.142.142.23 "GET /crabserver/preprod/workflowdb?getstatus=HOLDING&limit=10&workername=vocms045 HTTP/1.1" 500 Internal Server Error [data: 3781 in 726 out 38549 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=tw/vocms244.cern.ch" "" ] [ref: "" "CRABClient/0.0.0" ]
[24/Apr/2015:14:43:43]  RESTSQL:DxyIhNHGntJV release with rollback
```

**Comment by mmascher** [comment]
Hi @juztas , I moved `MultiProcessingLog` because we will need it in the client as well eventually. Getlog/getoutput have logs problem.

**Comment by juztas** [comment]
Ok, I agree, but still it should not be required to move or wget it by hand :)

**Comment by mmascher** [comment]
I have already updated the `setup.py`, sorry ahout that. Can you try and see if the other error is gone? I think I hit the wrong buttin in SQLDeveloper and executed just one SQL statement instead the whole list..

**Comment by juztas** [comment]
:+1:

**Comment by mmascher** [comment]
List of changes/validation tasks:

CLIENT
* Use the new `JobType.disableAutomaticOutputCollection` and try to break it. Meaning, use it with different psets (producing various combination of tfiles,edm and additional outputs), and see if the output can be retrieved/is transferd. Should have not broken anything with the default behavior, don't check.
* `crab status` shows more errors now. New modifications will come and I have already checket it works. Nothing to do.
* Remove SocketError exception. It was used with httplib, now we are using pycurl. Nothing to check, but keep your eyes open and trigger me if you see it!
* Fix in check status loop for dryrun case. Try to use the `--wait` option of submit, and also the dryrun. We fixed the handling of the `checkStatusLoop` done after the submission so the client hangs until the task is in a terminal state.
* The problem a user had with the pset loaded twice should be solved. Low priority get his task and try to replicate the error (would be good to add the sandbox to the automatic validation we do)

I hope I have not forgotten anything. As usual, also try the production client against preprod server (check backward compatibility is guaranteed)

SERVER
* Propagate errors in cmscp and postjob to the JSON job report file. crab status should show all the errors now, even when they come from ASO or cmscp or memory limits (I have checked the latter). In particular, we should not see again `Job exit code -1` and job succeded in the same sentence.
* outLFN and allowNonProductionCMSSW has been renamed. Check we print the warning that the parameter has changed.
* Try to submit with walltime bigger then and memory bigger then 2500. See if we get the warning and the correction.
* check warnings/errors for invalid datasets, or dataset that are only at T0. Messages should be clearer now.
* all the resubmit options should work now!! Try them (really important). In general we should re-validate the resubmit from scratch

These are the things I would focus more. Of course the usual tests are necessary.

**Comment by juztas** [comment]
Client still not showing removed due to memory [1] or waltime [2]
[1]
```
Task name:			150424_131425:jbalcas_crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryRM
Task status:			FAILED
Glidemon monitoring URL:	http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=150424_131425%3Ajbalcas_crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryRM
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150424_131425%3Ajbalcas_crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryRM
Details:			failed        100.0% (100/100)

No publication information available yet

Error summary:
37 jobs failed with exit code 50660:
	Not retrying job due to excessive memory use (job automatically killed on the worker node)
63 jobs failed with exit code -1:
	51 jobs failed with following error message:
		The framework job report could be loaded but no error message found there
	12 jobs failed with following error message:
		Invalid framework job report. The framework job report exists, but it cannot be loaded.
Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.
```
[2]
```
CRAB project directory:		/afs/cern.ch/work/j/jbalcas/VALIDATE/HG1505a/CMSSW_7_0_6/src/HG1505a-1/crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-RuntimeRM
Task name:			150424_131410:jbalcas_crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-RuntimeRM
Task status:			FAILED
Glidemon monitoring URL:	http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=150424_131410%3Ajbalcas_crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-RuntimeRM
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150424_131410%3Ajbalcas_crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-RuntimeRM
Details:			failed        100.0% (100/100)

No publication information available yet

Error summary:
1 jobs failed with exit code 50664:
	Not retrying job due to wall clock limit (job automatically killed on the worker node)
99 jobs failed with exit code -1:
	76 jobs failed with following error message:
		The framework job report could be loaded but no error message found there
	23 jobs failed with following error message:
		Invalid framework job report. The framework job report exists, but it cannot be loaded.
Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.
Log file is /afs/cern.ch/work/j/jbalcas/VALIDATE/HG1505a/CMSSW_7_0_6/src/HG1505a-1/crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-RuntimeRM/crab.log
```

**Comment by mmascher** [comment]
Interesting, the report is there for some jobs but not for other. I wonder if there is a pattern (maybe all the jobs that run at a site reports `Not retrying job due to wall clock limit`, and other does not)

**Comment by belforte** [comment]
@mmascher I do not see any job_out.*.*.txt with more then zero bytes for either task. What does it mean "the report is there" ?
Are we running 8.3.5 on all schedd's ? Is the same version needed for glideins as well ?

**Comment by juztas** [comment]
a) Not reporting correct exit message, because RetryJob did not got it. We (me and Andres) are checking right now one thing. Will let you know soon.
     1) Because it is not FatalError, job was retried and it should not.
b) Logs are not returned because we don`t have 8.3.5

**Comment by belforte** [comment]
but you pasted crab client snippets which says
37 jobs failed with exit code 50660:
    Not retrying job due to excessive memory use (job automatically killed on the worker node)

1 jobs failed with exit code 50664:
    Not retrying job due to wall clock limit (job automatically killed on the worker node)

Isn't this what we expect ?

Are you saying that all jobs in the tasks were supposed to end similarly but they did not ?

**Comment by juztas** [comment]
Yes, they should end similarly and they did what I see from condor_history or job_log

**Comment by juztas** [comment]
Here you go:
```
[jbalcas@vocms0114 cluster2276614.proc0.subproc0]$ condor_history -const 'CRAB_ReqName=?="150424_131425:jbalcas_crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryRM"' -af CRAB_Retry RemoveReason | sort | uniq -c
    100 0 Removed due to memory use
    100 1 Removed due to memory use
    100 2 Removed due to memory use
     85 3 Removed due to memory use
     45 4 Removed due to memory use
      4 5 Removed due to memory use
```

**Comment by juztas** [comment]
So I think we have a latency here: https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L71 as it tries to read RemoveReason from user_log and if condor have not updated it yet, we don't have RemoveReason.

Would be useful for us if we print read classads in Postjob and to get correct RemoveReason either PostJob could sleep or... suggestions ?

**Comment by belforte** [comment]
Can you expand a bit ?
Seems you are saying that DAGMAN starts postJob before user_log has been updated.
What do we find in user_log at that time ? Is the job status correct at least ?
Do I understand correctly your suggestion as "get class-ad via condor_q from schedd rather then condor_q -userlog job_log " ?

I do not like very much to introduce a simple sleep for X seconds here, we need some way to tell for sure if log was updated. Better yet DAGMAN should not start the postjob when things are still in flux.
 
 Also this seems general enough to affect all sort of tasks. Is RemoveReason the only thing that we try to get out of job_log in the postJob ?

**Comment by belforte** [comment]
could we possibly have a "shoot in my foot" effect where one postJob reading job_log prevents schedd from updating it for another job ? It seems that condor_history -userlog opens the log in write :-( Same with condor_q
(i.e. I can read the file, but condor_history refuses to process it [*])
@bbockelm I thought I hit this long ago in "Igor's times" and he had asked HTC developers to user read-only access to userlog, I thought it was fixed long ago. Does it ring any bell ? Could there be reasons why it has to be write access ? Or should we try to resurrect the request.

[*] belforte@vocms0114/cluster2276614.proc0.subproc0> head -1 job_log
000 (2276689.000.000) 04/24 15:15:18 Job submitted from host: <128.142.142.28:4080?noUDP&sock=3202218_176b_3>
belforte@vocms0114/cluster2276614.proc0.subproc0> condor_history  -userlog job_log  ID     OWNER          SUBMITTED   RUN_TIME     ST COMPLETED   CMD            
Error: Can't open userlog job_log
belforte@vocms0114/cluster2276614.proc0.subproc0>

**Comment by belforte** [comment]
HTCondor does not rellay try to open the userlog in Write. But puts a lock 
https://github.com/htcondor/htcondor/blob/5508514ed3ec1092d42c049cd122b40efb775909/src/condor_utils/read_user_log.cpp
Effect may be the same. I suspect one postJob reading prevents schedd from updating, with multiple postJobs running at same time a race condition seems possible, depending on the schedd logic, i.e. wether it really can declare a job done and allow DAGMAN to trigger the postJob before the log was written.

Well... I had enough fun, I guess. Comment from HTCondor expert is likely needed.

**Comment by mmascher** [comment]
Hi Stefano, we are using `condor_q -debug -l -userlog job_log` , does it also open the file in writeonly mode?

We might need to revert https://github.com/dmwm/CRABServer/commit/128a95151ff52afd8c3949659ae6549fae8a8ae1#diff-c509c79b3519772846fb1e0f6c5a220dL71 (see https://github.com/dmwm/CRABServer/issues/4264)

Anyway, I agree that once the postjob starts, all the events related to it's corresponding job should be in the job_log file. That way we can always find the `RemoveReason`. A `sleep` is not helping, and getting the `RemoveReason` querying the schedd... Well, it may be too much for it..

**Comment by belforte** [comment]
I was following up the condor_q code. So as I wrote it does not open in write, but puts a lock. So that when opening as non-owner I got:
belforte@vocms0114/cluster2276614.proc0.subproc0> condor_q  -debug -userlog job_log 
04/27/15 13:42:25 I am: hostname: vocms0114, fully qualified doman name: vocms0114.cern.ch, IP: 128.142.142.28, IPv4: 128.142.142.28, IPv6: 
04/27/15 13:42:25 I am: hostname: vocms0114, fully qualified doman name: vocms0114.cern.ch, IP: 128.142.142.28, IPv4: 128.142.142.28, IPv6: 
04/27/15 13:42:25 ReadUserLog::OpenLogFile safe_open_wrapper on job_log returns -1: error 13(Permission denied)
04/27/15 13:42:25 ReadUserLog::initialize: error opening file

I have no tried concurrent opening from the directory/file owner, it is not immediately easy.

But indeed  #4264 seems to say that those locks are a thing of the past, so there should be no problem of multiple postJobs reading same file. I don't really know/understand condor enough to tell. But this lock thing is only about "one possible reason why it is so frequent to read the log before it is updated". It seems clear that postJob starts and reads the log before being sure that log is up to date. Which of course is bad. But if problem is in the schedd/DAGMN handshake, doing the reverting you indicate may only make the issue less frequent, not solve it.

**Comment by juztas** [comment]
Here seems to be not correct. From this task only 
http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms0114.cern.ch/mon/cms1761/150427_080034:jbalcas_crab_HG1505b-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-voGroupescms/postjob.69.0.txt 

https://github.com/dmwm/CRABServer/blob/6dda4f16c16c2200e147a1b4a16d7563a67a0c0e/src/python/TaskWorker/Actions/RetryJob.py#L187-L189

**Comment by juztas** [comment]
http://glidemon.web.cern.ch/glidemon/jobs.php?taskid=1074095 this task was with reverted patch

**Comment by belforte** [comment]
each jobs was resubmitted O(14-17) times in there. It does not seem to agree with my understanding 
from the meeting.

**Comment by juztas** [comment]
I am not changing TW code. I change directly on schedd RetryJob.py and tested out there for that task.

**Comment by AndresTanasijczuk** [comment]
@juztas But said that the crab status error summary is still not correct? If that's the case, can you paste here what is the error summary from crab status?

**Comment by juztas** [comment]
All last postjobs are reporting correctly, but seems error_summary was not updated or not last retry was taken. 
```
[jbalcas@lxplus0101 src]$ crab status HG1505a-1/crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryRM/
CRAB project directory:		/afs/cern.ch/work/j/jbalcas/VALIDATE/HG1505a/CMSSW_7_0_6/src/HG1505a-1/crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryRM
Task name:			150424_131425:jbalcas_crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryRM
Task status:			FAILED
Glidemon monitoring URL:	http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=150424_131425%3Ajbalcas_crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryRM
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150424_131425%3Ajbalcas_crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryRM
Details:			failed        100.0% (100/100)

No publication information available yet

Error summary:
7 jobs failed with exit code 50660:
	Not retrying job due to excessive memory use (job automatically killed on the worker node)
93 jobs failed with exit code -1:
	Invalid framework job report. The framework job report exists, but it cannot be loaded.
Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.
Log file is /afs/cern.ch/work/j/jbalcas/VALIDATE/HG1505a/CMSSW_7_0_6/src/HG1505a-1/crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryRM/crab.log
```

If I test new task with my fix, seems everything is correct:
```
[jbalcas@lxplus0101 src]$ crab status
CRAB project directory:		/afs/cern.ch/work/j/jbalcas/VALIDATE/HG1505a/CMSSW_7_0_6/src/HG1505a-1/crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryNew
Task name:			150427_155050:jbalcas_crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryNew
Task status:			FAILED
Glidemon monitoring URL:	http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=150427_155050%3Ajbalcas_crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryNew
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150427_155050%3Ajbalcas_crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryNew
Details:			failed        100.0% (10/10)

No publication information available yet

Error summary:
10 jobs failed with exit code 50660:
	Not retrying job due to excessive memory use (job automatically killed on the worker node)
Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.
Log file is /afs/cern.ch/work/j/jbalcas/VALIDATE/HG1505a/CMSSW_7_0_6/src/HG1505a-1/crab_HG1505a-1-MinBias_PrivateMC_EventBased_ExtraParams-L-T_O-T_P-T-MemoryNew/crab.log
```

So my though here if we have a lot of different errors, error_summary is not updated with latest one and it is showing older errors

**Comment by bbockelm** [comment]
@belforte FYI - locking is disabled on =condor_q= by the following line:

https://github.com/dmwm/CRABServer/blob/6bcc8484f24bbb559f124ec462f0ea12660def53/src/python/TaskWorker/Actions/RetryJob.py#L19

(I did give a recipe - which I think is still useful and valid - in January to avoid touching job_log completely there.  Would also save a lot of CPU time in parsing.)

**Comment by AndresTanasijczuk** [comment]
@juztas crab status error summary reads the message from the last job retry. So, do you think we have a problem or not?

**Comment by belforte** [comment]
OK, so I was off track. Yet something not good was going on.
We could avoid reading job_log, but it was not expected to be an unreliable source
of information :-(

**Comment by juztas** [comment]
@AndresTanasijczuk I think yes. So here is what I founded out:
Seems that during same time several PostJobs are running as we have a limit of 20 as you know. Each PostJob is reading "all job_fjr.%s.%s.json" and tries to update error_summary in each postJob variable. [1]
If PostJob is not able to determine exitCode or exitMsg it raise exception and msg becomes [2] and write this into error_summary [3].  (Is there a lot of cases where job_fjr can`t be loaded or exitMsg or exitCode is not defined?). In that case next PostJob will not be able to change exitMsg, because this job_id and retry_id is already defined in error_summary [4]. It might be also that this was trigerred due to a lot kill/resubmit/kill/resubmit 

[1] https://github.com/dmwm/CRABServer/blob/23230ba35a70935a62defbc6e1b2649fa1ab908a/src/python/TaskWorker/Actions/PostJob.py#L131-L170
[2] https://github.com/dmwm/CRABServer/blob/23230ba35a70935a62defbc6e1b2649fa1ab908a/src/python/TaskWorker/Actions/PostJob.py#L166
[3] https://github.com/dmwm/CRABServer/blob/23230ba35a70935a62defbc6e1b2649fa1ab908a/src/python/TaskWorker/Actions/PostJob.py#L131-L170
https://github.com/dmwm/CRABServer/blob/23230ba35a70935a62defbc6e1b2649fa1ab908a/src/python/TaskWorker/Actions/PostJob.py#L134-136

**Comment by AndresTanasijczuk** [comment]
Right @juztas , the problem is then that since the job_fjr files are created at the beginning when a PostJob runs, while the exitMsg and exitCode are obviously added near the end of the PostJob execution, the exitMsg and exitCode are not propagated to the error_summary if another PostJob has already written that jobid and retry to the error summary. We can:
- Change the prepareErrorSummary to not read all the "job_fjr.%s.%s.json" files but only the one for the given jobid and retry. But this means that errors will not appear in the error summary until the postjob for that jobid/retry finishes execution.
- Change the prepareErrorSummary to not write to the error summary if exitCode or exitMsg was not found.
- Change the prepareErrorSummary to allow overwrite the error_summary for existing jobids and retries. But then the error summary from the status will show error message "Invalid framework job report. The framework job report exists, but it cannot be loaded." until the real exitMsg from postjob is written to the error summary. This may cause some confusion.
- Any other proposition?

**Comment by AndresTanasijczuk** [comment]
I prepared a patch in https://github.com/dmwm/CRABServer/pull/4778 @juztas can you try it in the task where you have still 93 jobs failed with exit code -1 ? I mean change the PostJob.py in the spool dir for that task and resubmit. The patch doesn't write the the error summary the msg 'Invalid FJR' is the jobid and retry are not the ones for which this post-job corresponds. I think this is the best we can do. Or do you foresee any problem?

**Comment by juztas** [comment]
I will test later today.
Next question, is it needed system_periodic_remove on scheduler for DiskUsage? We have this check in crab, but if system_periodic_remove is raised, we are not able to determine RemoveReason
```
001 (2336170.000.000) 04/27 13:02:00 Job executing on host: <172.17.36.22:43095?CCBID=128.142.141.17:9650#275655%20128.142.141.24:9650#272391&noUDP>
...
009 (2329786.000.000) 04/27 13:02:24 Job was aborted by the user.
	The system macro SYSTEM_PERIODIC_REMOVE expression '(((JobUniverse=!=7)&&(((NumJobStarts>9)=?=True)||((NumShadowStarts>19)=?=True)))) || ((DiskUsage>27000000)=?=True)' evaluated to TRUE
...
009 (2330502.000.000) 04/27 13:02:26 Job was aborted by the user.
	The system macro SYSTEM_PERIODIC_REMOVE expression '(((JobUniverse=!=7)&&(((NumJobStarts>9)=?=True)||((NumShadowStarts>19)=?=True)))) || ((DiskUsage>27000000)=?=True)' evaluated to TRUE
...
016 (2330502.000.000) 04/27 13:02:33 POST Script terminated.
	(1) Normal termination (return value 1)
    DAG Node: Job29
...
016 (2329786.000.000) 04/27 13:02:33 POST Script terminated.
	(1) Normal termination (return value 1)
    DAG Node: Job3
```

**Comment by juztas** [comment]
```
[jbalcas@lxplus0101 src]$ crab getoutput HG1505b-1/crab_HG1505b-1-MinBias_PrivateMC_EventBased-L-T_O-T_P-T_IL-T-DOC-T/
No files to retrieve.
This is normal behavior if General.transferOutputs=False is present in the task configuration.
```
Can we improve this error message? I used 'config.JobType.disableAutomaticOutputCollection = True' and have not specified any outputFiles

**Comment by juztas** [comment]
I would guess it should be sorted:
```
crab tasks --instance=preprod
....
--------------------------------------------------------------------------------
150408_145305:jbalcas_crab_835condor_load_memory602570
								SUBMITTED
--------------------------------------------------------------------------------
150408_145322:jbalcas_crab_835condor_load_memory139676
								SUBMITTED
--------------------------------------------------------------------------------
150408_145333:jbalcas_crab_835condor_load_memory924247
								SUBMITTED
--------------------------------------------------------------------------------
150408_145345:jbalcas_crab_835condor_load_memory937888
								SUBMITTED
--------------------------------------------------------------------------------
150408_145442:jbalcas_crab_835condor_load_memory1246950
								SUBMITTED
--------------------------------------------------------------------------------
150324_095219:jbalcas_crab_HG1504a-2-MinBias_PrivateMC_EventBased-L-T_O-T_P-T_IL-F-dryRun
								UPLOADED
--------------------------------------------------------------------------------
150401_064607:jbalcas_crab_HG1504a-2-Analysis_LumiBased_on_Data-1
								UPLOADED
--------------------------------------------------------------------------------
```

**Comment by belforte** [comment]
about https://github.com/dmwm/CRABServer/issues/4765#issuecomment-96835448
(do you really want to have all of those different topics in this same git issue with such a generic subject ?)

The first thing is to be more clear about the flow. You make it sound like various parts of postJob take actions in changing the exit code and/or reporting status to client, and are trying to orchestrate them in a complex way, somehow ad hoc for this particular problem.
I'd rather go to the root of the issue and make it clear what happens. As usual it appears there are more job statuses than expected, "waiting for postJob to run" is not well defined and apparently treated in inconsistent way. I agree that a solution for the problem of the day could be find along the lines you indicated (am not familiar enough with details to say upfront which one), but I would prefer that this done not "because it works", but "because it fits the design", so that such a design can be consistently applied to other parts of the code as well.

**Comment by AndresTanasijczuk** [comment]
@belforte I wrote a detailed description of the problem and the solution I propose in https://github.com/dmwm/CRABServer/issues/4780 We can follow up there.

**Comment by belforte** [comment]
really nice. THanks.

**Comment by belforte** [comment]
is this validation done and can this hence be closed ?

**Comment by juztas** [comment]
Done.
